repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    - id: add-trailing-comma
      args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    - id: pyupgrade
      args: [--py37-plus]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      additional_dependencies: [types-all,'sqlalchemy[mypy]']
      exclude: "migrations"
