version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
